name = "TensorKitIO"
uuid = "f66f1535-d0b7-4619-80d5-9ee19d431941"
authors = ["Yue Zhengyuan <yuezy1997@icloud.com>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PEPSKit = "52969e89-939e-4361-9b68-9bc7cde4bdeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
JLD2 = "0.6"
PEPSKit = "0.6,0.7"
Printf = "1.11"
TensorKit = "0.14,0.15"
